spring.application.name=alabbas-store
spring.datasource.url=jdbc:postgresql://localhost:5432/alabbas_db
spring.datasource.username=postgres
spring.datasource.password=pass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8081
app.upload.images-path=D:/El abbas/alabbas-store/images

app.jwt.secret=ThisIsASecretKeyForAlAbbasStoreJwtTokenMustBeLongEnough123456
app.jwt.expiration=86400000
